#include "Robot_objects.h"
void read_uart();
void Check_Joystic();
unsigned short tmp, DataReady;
char txt_Bt[200];
char txt_GPS[768];
unsigned short ready;
int gg=0;
int bb=0;


// Uart Rx interrupt handler
void interrupt(){
  if (PIR1.RC1IF == 1) {                        // Do we have uart rx interrupt request?
    tmp = UART1_Read();                        // Get received byte
      if (tmp == 13) {                         // check for CR
        txt_Bt[bb] = 0;                            // Puting 0 at the end of the string
        DataReady = 1;                         // Data is received
      }
      else {
        if (tmp != 10){
          txt_Bt[bb] = tmp;                          // Moving the data received from UART to string txt[]
          bb++;
        }
      }
   PIR1.RC1IF = 0;
   }
   
  if (RC2IF_bit == 1) {             // If interrupt is generated by RCIF
    txt_GPS[gg] = UART2_Read();         // Read data and store it to txrt string
    gg++;                           // Increment string index
    if (gg == 768) {                // If index = 768,
        gg = 0;                       //   set it to zero
        ready = 1;                     // Ready for parsing GPS data
  }
  RC2IF_bit = 0;                    // Set RCIF to 0
  }
}
// Sends constant message via UART (without carriage return)


void main() {
  Start_TP();
  while (1) {
    Check_TP();
    read_uart();
    Check_Joystic();
    }
}